config/routes.rb
Rails.application.routes.draw do
  root to: 'public#index'

  # auth routes
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  devise_scope :admin do
  	get 'admin', to: 'devise/sessions#new'
  end
  devise_for :admins

  get 'admin_panel', to: 'admin#index', as: :admin_root
  resources :items, only: [:index, :update, :create, :destroy]
  resources :deals, only: [:index, :create, :destroy]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :buyer, class_name: 'User'
  belongs_to :seller, class_name: 'User'
  belongs_to :item
  has_many :offers

  def buyer_name
  	buyer.try(:username)
  end

  def seller_name
  	seller.try(:username)
  end
end

app/models/depot.rb
class Depot < ActiveRecord::Base
  belongs_to :user
  has_many :depots_items
  has_many :items, through: :depots_items
end

app/models/depots_item.rb
class DepotsItem < ActiveRecord::Base
  belongs_to :depot
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product
  accepts_nested_attributes_for :product

  def total_price
  	self.price*self.quantity
  end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :login

	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, authentication_keys: [:login]

	validates :username, presence: true, uniqueness: { case_sensitive: true }
	# Only allow letter, number, underscore and punctuation
	validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

	has_one :depot

	def self.find_for_database_authentication(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions.to_hash).where(["username = :value OR email = :value", { :value => login.downcase }]).first
		elsif conditions.has_key?(:username) || conditions.has_key?(:email)
			where(conditions.to_hash).first
		end
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
  def authenticated_user_or_admin
    user_signed_in? || admin_signed_in?
  end

  private
    def build_potential_new_objects
      @new_item = Item.new
      @new_deal = Deal.new
    end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticated_user_or_admin

  def index
  end

  def create
  	deal = Deal.create(allowed_params)
  	if deal.valid?
  	  return render json: deal
  	else
  	  return render json: { "error": "Não foi possível criar negociação" }
  	end
  end

  def destroy
  end

  private
  	def allowed_params
      params.require(:deal).permit(:buyer_id, :seller_id, :item_id, :deal_type)
  	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticated_user_or_admin
  before_action :authenticate_admin!, only: [:index]

  respond_to :json

  def index
  end

  def create
  	item_params = allowed_params
  	product_params = item_params["product"]
  	product = Product.find_or_create_by(product_params)

  	item_params["product"] = product
  	item = Item.create(item_params)

  	if item.valid?
  	  DepotsItem.create(depot: current_user.depot, item: item)
      render json: item
    else
    	render json: { "error": "Não foi possível adicionar o item" }
    end
  end

  def destroy
  	item = Item.find(params[:id])
  	current_user.depot.items.delete(item)
  	item.destroy
  	redirect_to :back
  end

  private
  	def allowed_params
      params.require(:item).permit(:quantity, :price, product: [:name, :category_id])
  	end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
    build_potential_new_objects
    if user_signed_in?

      user = current_user
      @depot = user.depot

      @deals_buy = Deal.where(buyer: current_user)
      @deals_sell = Deal.where(seller: current_user).includes(:item)
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  clear_respond_to
  respond_to :json

  def create
  	super do |resource|
  		Depot.create(user: resource)
  	end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  clear_respond_to
  respond_to :json
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.slim
header
  .row
    .col-lg-6
      h1
        = link_to "MarketV", :admin_root
  .col-lg-6
      = "Bem vindo #{current_admin.fullname}"
      = link_to "Sair", :destroy_admin_session, method: :delete

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/deals/_deals_list.html.slim
table.table.table-bordered.table-striped.table-hover
  thead
    th Comprador
    th Vendedor
    th Criada em
    th Mercadoria
    th Categoria
    th Quantidade
    th Preço (unid.)
    th Preço (total)
    th Ações
  tbody
    - deals.each do |deal|
      tr
        td = deal.buyer_name
        td = deal.seller_name
        td = deal.created_at
        td = deal.item.product.name
        td = deal.item.product.category.name
        td = deal.item.quantity
        td = deal.item.price
        td = deal.item.total_price

app/views/deals/_new_deal.html.slim
#newDealModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h4.modal-title Criar negociação
      .modal-body
        - if user_signed_in?
        = simple_form_for @new_deal, url: deals_path, html: { class: "new-deal-form", data: {"my-id": current_user.try(:id) } }, remote: true do |f|
          = f.input :buyer_id, as: :hidden
          = f.input :seller_id, as: :hidden
          = f.input :deal_type, as: :radio_buttons, collection: [["Compra", "buy"], ["Venda", "sell"]]
          = f.input :item_id, collection: current_user.depot.items.map { |i| [i.product.name, i.id ]}
          = f.submit "Criar"

javascript:
  $("form.new-deal-form").on("submit", function(e){
    var dealType = $(this).find('#deal_deal_type_buy').is(':checked') ? "buy" : "sell";
    var currentUserID = $(this).data("my-id");

    if(dealType == "buy") $(this).find("#deal_buyer_id").val(currentUserID);
    else $(this).find("#deal_seller_id").val(currentUserID);
  });

  $("form.new-deal-form").on("ajax:success", function(){
    location.reload();
  });

  $("form.new-deal-form").on("ajax:error", function(){
    alert("Erro ao criar negociação");
    $("#newDealModal").modal("hide");
  });  

app/views/items/_edit_item.html.slim
#editItemModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h4.modal-title Edição de mercadoria
      .modal-body
        = simple_form_for :item, url: item_path(0), html: { class: "edit-item-form" }, remote: true do |f|
          = f.input :id, as: :hidden
          = f.input :quantity
          = f.input :price
          = f.submit "Salvar"

javascript:
  $(".js-edit-item").on("click", function(){
    var id = $(this).data("id");
    var quantity = $(this).data("quantity");
    var price = $(this).data("price");

    var $editForm = $("#editItemModal form");
    $('input[name="item[id]"]', $editForm).val(id);
    $('input[name="item[quantity]"]', $editForm).val(quantity);
    $('input[name="item[price]"]', $editForm).val(price);
  });

  $("form.edit-item-form").on("ajax:success", function(){
    location.reload();
  });

  $("form.edit-item-form").on("ajax:error", function(){
    alert("Erro ao editar");
    $("#addProductModal").modal("hide");
  });  

app/views/items/_new_item.html.slim
#addItemModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h4.modal-title Adicionar mercadoria a depósito
      .modal-body
        = simple_form_for @new_item, url: items_path, html: { class: "add-item-form" }, remote: true do |i|
          = i.simple_fields_for Product.new do |p|
            = p.input :name
            = p.association :category, include_blank: false
          = i.input :quantity
          = i.input :price
          = i.submit "Criar"

javascript:
  $("form.add-item-form").on("ajax:success", function(){
    location.reload();
  });

  $("form.add-item-form").on("ajax:error", function(){
    alert("Erro ao adicionar mercadoria");
    $("#addItemModal").modal("hide");
  });  

app/views/layouts/application.html.slim
doctype html
html
  head
    title Market V
  	= csrf_meta_tags
    = stylesheet_link_tag 'init_public', media: 'all'
    = javascript_include_tag 'init_public', media: 'all'
  body
    .container
  	  = yield

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>